# Generated by Django 3.2 on 2024-05-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stage_cleart',
            field=models.IntegerField(default=0),
        ),
    ]
